MENU:
  TITLE: '  &c&lDo you admit the use of hacks?'
  SLOTS: 27
  ITEMS:
    SS:
      ID: 152
      DATA: 0
      SLOT: 11
      DISPLAYNAME: '&c&lNO, SS PLS'
      LORE:
        - '&7Exaple lore'
    ADMIT:
      ID: 133
      DATA: 0
      SLOT: 15
      DISPLAYNAME: '&c&lI ADMIT THE USE OF HACKS.'
      LORE:
        - '&7Exaple lore'
REMINDER:
  TIMER: 1
  TIMER_ADMIT_LIMIT: 90 #In Seconds
  SOUND:
    ENABLED: true
    SOUND: ITEM_BREAK
  CHAT:
    ENABLED: true
    MESSAGE: '&c&lDo you admit the use of hacks? %seconds% remaining'
SS_USE: '&cUse: /ss <player>'
SS_ADMIT: '&7[&c&lSS&7] &d%player% &eadmitted the use of hacks.'
SS_NO_ADMIT: '&7[&c&lSS&7] &d%player% &erequest an ss.'
SS_TIMEOUT: '&7[&c&lSS&7] &d%player%''s &etime has expired to admit the use of hacks.'
TARGET_NOT_FOUND: '&7[&c&lSS&7] &d%player% &enot found.'
TARGET_FREEZE: '&7[&c&lSS&7] &eThe player &d%player% &ehas been frozen.'
TARGET_UNFREEZE: '&7[&c&lSS&7] &eThe player &d%player% &ehas been unfrozen.'
NO_HAVE_PERMISSION: '&cYou don''t have permission.'